### ISSUE TITLE
FeatureRequest: Option to restrict backlog view to own tickets

### ISSUE THREAD

**Issue by mgexo** [jszakmeister/trac-backlog#16]
Maybe, I am missing something ( if so, please explain):

Currently, backlog shows tickets of all users at the same time.

This view is only useful for the "project-leader" / "head of development". 

Each individual developer should only see his own tickets by default. This should be configurable in the Backlog-Preference setting.

As future extension, one should be able to add/remove people to his backlog view, for the use case when a few people work on the same tasks at the same time. 

Important: This should only restrict the displayed view on the ticket, not the actual order of all tickets, i.e.: In any case, the order of  tickets should still be the same for all users, such that the "project-leader" can re-order tickets of all developers, and each individual developer can change order of the tickets that they own.

**Comment by jszakmeister** [comment]
I've never treated this as a list of work that _I_ need to get done, but rather the backlog of work _to_ get done.  So you're not missing anything, but it sounds like what you're looking for is different than the mindset I had when I wrote this.

I don't think I agree with the idea that each developer should see his own tickets by default... that really wasn't the intent.  You could, however, probably generate a report that shows the tickets in rank order for the person currently logged in.

I just want to be clear.  I didn't intend for the backlog plugin to be a system for Agile development.  I wrote it because Trac mostly solved our needs, but we really needed a way to prioritize tickets.  You may want to check out Agilo if you find you really need something more.

**Comment by mgexo** [comment]
Ah ok I see, thank you for your feedback. 

The thing is, that we have like 200 open tickets in our system, and people that do not share common work tasks cannot even understand all the tickets that appear there. So we would need that filter. 

But, If that was not your design goal its ok. I will check if Agilo could help us.

Thank you very much
